
image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376

before_script:
  #- docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://registry.stud.idi.ntnu.no:5050
  - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN registry.stud.idi.ntnu.no:5050

build:
  image: docker:20.10.16
  # run on a gitlab-runner that is configured with docker-in-docker
  tags:
    - dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  script:
    - docker -v
    # use previous image as a cache to speedup build process
    # - docker pull $CI_REGISTRY_IMAGE:latest || true
    # use git tag to tag the image
    - docker build -f GitlabDockerfile --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker -v

pages:
  script:
  - apk update && apk add doxygen
  - doxygen docs/Doxyfile
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
