#!/bin/bash
wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/2.3.1/gatling-charts-highcharts-bundle-2.3.1-bundle.zip -P ~
unzip ~/gatling-charts-highcharts-bundle-2.3.1-bundle.zip -d ~
echo Gatling Stress Tool installed
