#!/bin/bash
cp -r gatling/chat ~/gatling-charts-highcharts-bundle-2.3.1/user-files/simulations
cp gatling/usernames.csv ~/gatling-charts-highcharts-bundle-2.3.1/user-files/data
~/gatling-charts-highcharts-bundle-2.3.1/bin/gatling.sh