#!/bin/bash
cp -r gatling/chat ~/gatling-charts-highcharts-bundle-3.9.1/user-files/simulations
cp gatling/usernames.csv ~/gatling-charts-highcharts-bundle-3.9.1/user-files/resources
~/gatling-charts-highcharts-bundle-3.9.1/bin/gatling.sh