#!/bin/bash

if ! [ $(id -u) = 0 ]; then
   echo "This script needs to be run as root." >&2
   exit 1
fi

clear
echo "Starting logsystem..."
glances -C glances.conf --export influxdb2 -q &
echo "Done."
