#!/bin/bash
sudo apt update
sudo apt install openjdk-8-jdk wget gnupg docker docker-compose

wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

sudo apt update
sudo apt install jenkins
sudo gpasswd -a jenkins docker
sudo systemctl daemon-reload
sudo systemctl restart docker
sudo service jenkins start

clear
echo "Henter ut ditt Adminpassord..."
sleep 5
sudo cat /var/lib/jenkins/secrets/initialAdminPassword

sudo service jenkins restart
